### ISSUE TITLE
Curriculum committee spreadsheet

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-curriculum#1]
Our readme.md should include a link to the spreadsheet to be used at our meetings -- to record attendance and tally votes on proposals.

As specified in the committee procedures issue: https://github.com/foundersandcoders/london-programme/issues/183

**Comment by bradreeder** [comment]
Closed #2

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#356
