### ISSUE TITLE
Stop-go-continue minutes from past FACs

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-curriculum#13]
It is likely worth updating our stop-go-continue folder here with the stop-go-continue minutes of past FACs. That way we will have a permanent record of them all in one place.

**Comment by iteles** [comment]
Could we merge them in rather than copy-paste? I'm loathe to lose the history

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#362
