### ISSUE TITLE
Number of graduate projects for FAC10

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/london-curriculum#16]
This time around we just about managed to sort out graduate projects for everyone that wanted them and here is what the schedule is beginning to look like for FAC10:

|Week|Description|Projects|Decided by| |
|----|----|----|----|----|
|13|IP Cortex|1|Week 14||
|14|To be decided|?|Week 14||
|15|Anna Freud|2|Week 15||
|16|dwyl|1|Week 16|***added 27/2***|

I am going to aim to get an extra employer project in place for Week 14. I am also going to aim to get 2 projects in for Week 16. That will be 6 projects for 12 people in total. This will potentially leave us 4 short, but given the rate at which graduates have been successful at getting jobs in the past, I am hopeful that this will be sufficient (5 FAC9ers have got permanent employment already).

**Comment by bradreeder** [comment]
@sofer I think 12 is a good number to aim for for FAC10. Do we need to account for the students of FAC Nazareth in this or are their graduate projects being handled separately?

Another possibility is that we could do the weeks 10-12 internal projects with actual clients. But I guess we should decide this at the next meeting?

**Comment by iteles** [comment]
Does this mean the last 4 weeks are now optional?

**Comment by nelsonic** [comment]
@sofer could @dwyl be considered for one of the student project weeks e.g: **16** ...? 🤔 
(_we have offered in the past - including the original Indiegogo campaign - we can even `assign` a "senior" person to mentor the F&C team during the project ... fairly certain @naazy / @SimonLab will be "up" for coaching the students... **all** our code is Open Source, so students can use it as "portfolio"..._)

**Comment by sofer** [comment]
@nelsonic that would be amazing, amazing.

**Comment by sofer** [comment]
@iteles the last 4 weeks are not optional at all. In the table above, I am attempting to describe the weeks in which graduate projects will be selected. e.g. the Anna Freud week (14) will lead to two graduate projects that will be decided in Week 15 and will start after Week 16.

**Comment by bradreeder** [comment]
@nelsonic @iteles The format for weeks 10-12 is still in formation. But the current outline is to do a 3 week group project covering:

* a design sprint
* agile workflow / team roles
* user-test prototype with actual users & then plan next sprint off basis of feedback
* full-stack MVP (as a means of bringing together everything from the taught course.)
* chance for students to learn new technology of choice

The idea being that we can teach them about agile/ lean, ux/ user-testing, working with clients, etc, through a project that's as close to the real thing as we can plan.

We could have them build something useful for FAC or dwyl, as the clients / projects haven't been decided. I'd be interested in collaborating if you wanted to, especially given I'm wanting to learn more about the way dwyl does project-management from you both anyway.

**Comment by sofer** [comment]
@nelsonic does dwyl want to do a whole-cohort workshop+design sprint as well, with some charity clients? If so, that would be 2 wonderful 4 words.

**Comment by bradreeder** [comment]
@sofer 's suggestion is another option 😅

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#365
