### ISSUE TITLE
Workshops without design sprints

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/london-curriculum#18]
We are running out of slots for design sprints, but I still have several potential clients that I am keen for us to work with on graduate projects. 

So, for FAC10 I propose to offer a couple of slots for workshops without design sprints and proceed straight to graduate projects. 

Wish me luck!

**Comment by bradreeder** [comment]
What week are we considering adding them to @sofer ?

**Comment by bradreeder** [comment]
@sofer We can always propose shortening the outline for weeks 10-12 so that we can fit in more time for client-workshops. Me and @des-des will work on a proposal for it at the soonest opportunity so we'll have an idea of how much time we have in the latter part of the curriculum.

**Comment by sofer** [comment]
@bradreeder we'll work something out! 

Thank you for being willing to offer a day in Weeks 10-12. Week 13 is also a good candidate week.

**Comment by jsms90** [comment]
Very old issue. Now being dealt with in `master-reference`. @sofer happy to close?

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#366
