### ISSUE TITLE
Mentor's s-g-c notes

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-curriculum#21]
@jsms90 @njsfield Can you upload the pictures you took here of the mentor's s-g-c notes and I'll add them to the s-g-c folder when I'm back?

(i.e. those for weeks 1, 2, 3, etc.)

**Comment by njsfield** [comment]
I think @jsm90 you should have the photos for the first week if I remember?

**Comment by bradreeder** [comment]
Closed #24

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#367
