### ISSUE TITLE
change week 8 - jumping to oauth before understanding more fundamental concepts

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/london-curriculum#47]
#### FAC9
+ During my cohort, many of us had a very shakey understanding of the concepts behind what was going on, despite managing to implement OAuth in our project.  
+ Even though we had 3rd party login working and put our access token in a JWT, many people were still largely in the dark about concepts (session management, authentication vs authorisation) & how everything fits together
+ [week 8 stop go continue](https://github.com/foundersandcoders/master-reference/issues/34#issuecomment-266883302) (main action points only)
#### Planning
+ Whilst planning week 8, I learned that most alumni _still_ seem quite in the dark about the concepts of the week _now_. This tells me that the learning outcomes of the week were never really achieved. I have not heard anyone say that this week was a success in their cohort.  
  + If students don't go on to do any authentication / authorisation / session management in their first job, they never have the opportunity to learn / consolidate these topics.
  + Covering this during the course, but covering it badly, makes it much more daunting to talk about during interviews / makes the learning curve more painful during their first job
+ I have learned _loads_ by planning this week, but everything I know was learnt _after_ the course
+ See [this issue](https://github.com/foundersandcoders/master-reference/issues/34) for how the curriculum design decisions were made this time round
#### FAC10
+ [week 8 stop go continue](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-8.md)

### Problems
+ Authentication left to a research topic - this is NOT enough. All teams should have a _thorough_ introduction to schemes & strategies.  
Creating your own hapi plugin doesn't seem so daunting if you understand how these work
+ Authentication (in general) is only introduced as part of oauth - some teams haven't implemeted a normal username & password login before logging in with a 3rd party
+ Validation is essentially a stretch goal during hapi week. Password validation is never practiced during OAuth week (because login is done through a 3rd party)
+ Cookies as the only form of session management, even though they have just been introduced to databases
+ Session management & authentication are each introduced & implemented for the first time in the same flow - causes confusion about which problem is being solved by which thing
+ _Horrendous_ introduction to security concerns i.e. a research topic

### Proposal
Week 8 should be called **hapi week 2**

It should include:
  + authentication (hapi: schemes & strategies)
  + authorisation (hapi: scopes)
  + session management - cookies _and_ database

We should remove:
  + OAuth

### Attempts to solve (so far)
+ hapi week mentors created a [morning challenge / workshop on cookies](https://github.com/foundersandcoders/hapi-auth-cookie-ws) (so it's not left purely to a research topic) & auth (should probably be left to week 8, but I think this was because FAC10 had a 4 day week, and we were trying to fit everything in a shorter space of time)  
[Needs a bit of work](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-7.md#stop)
+ Introduction to hapi authentication, through a [morning challenge](https://github.com/jsms90/hapi-authentication-workshop) - still not quite sufficient imo
+ add authentication walkthrough (separate from OAuth)
+ stop during walkthrough to point students to local storage, session storage, IndexedDB & cookies sections in chrome dev tools - to show that cookies aren't only storage option
+ add SSL/TLS certificate to OAuth workshop - make sure students aren't developing over an insecure connection - should be introduced better!
+ give more explanation of encryption - don't just leave it to a research topic ([but this is not best placed in the JWT workshop](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-10/cohort-week-8.md))

### Content (pre-FAC10)
**hapi week**
[Research topics](https://foundersandcoders.gitbooks.io/fac9/content/week5/readme_topics.html)
  + Validation - [FAC9](https://github.com/FAC9/READMES/blob/master/hapi/validation.md)
  + Authentication - [FAC9](https://github.com/FAC9/READMES/blob/master/hapi/authentication.md)
  + Caching & cookies - [FAC9](https://github.com/FAC9/READMES/blob/master/hapi/cache-and-cookies.md)
  + Templating - [FAC9](https://github.com/FAC9/READMES/blob/master/hapi/Templating.md)

**OAuth week**
[Week structure](https://foundersandcoders.gitbooks.io/fac9/content/week8/)
+ [OAuth workshop](https://foundersandcoders.gitbooks.io/fac9/content/week8/workshop.html) (steps 5-6 were "bonus" steps for FAC8)
+ [Research day topics](https://foundersandcoders.gitbooks.io/fac9/content/week8/readme_topics.html)
  + Authentication - [FAC9](https://github.com/FAC9/READMES/blob/master/oauth/authentication.md)
  + Authorisation - [FAC9](https://github.com/FAC9/READMES/blob/master/oauth/authorisation.md)
  + Cookies & local storage - [FAC9](https://github.com/FAC9/READMES/blob/master/oauth/cookies-and-local-storage.md)
  + JWTs - [FAC9](https://github.com/FAC9/READMES/blob/master/oauth/jwts.md)

### Content (FAC10)
Hapi week:
+ [Research topics](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-7/research-afternoon.md)
  + Validation
  + Authentication
  + Cookies & caching
  + Templating with helper functions
+ [hapi auth cookie workshop](https://github.com/foundersandcoders/hapi-auth-cookie-ws)
OAuth week (4 days - no research topics):
[Week structure](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-8/4-day-week/schedule.md)
+ [OAuth workshop](https://github.com/foundersandcoders/oauth-workshop) - adapted version
+ [Research day topics](https://foundersandcoders.gitbooks.io/fac9/content/week8/readme_topics.html)
  + Authentication
  + Authorisation
  + Security

**Comment by mcelearr** [comment]
To back @jsms90 up, I left the course having never successfully made a JWT, set a cookie or an 'authorization' header. Which is testament to the fact that this bit of the course was a bit shaky.

I actually feel like everyone in the Nazareth cohort has a good grasp of the learning outcomes for the week. We taught Oauth alongside standard authentication and session management. I think Oauth is quite a tough thing to learn on your own, is widely used and is pretty useful, so I would vote to keep it in the course and keep teaching it in the same week as the fundamentals.

**Comment by jsms90** [comment]
Proposal passed in Summer Cohort 2017 planning meeting

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#375
