### ISSUE TITLE
Purpose of Curriculum Committee

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-curriculum#5]
### Agenda item: Purpose of Committee

The purpose of the curriculum committee with accompanying action steps.

### Why

A) The master-reference is scaling quickly in terms of the number of issues and conversations occurring there. This means that it tends to only have a few dedicated contributors who can keep up with it, and others may feel out of the loop on decisions they disagree with. Staff like course coordinators, whose job role is to maintain the master-reference, end up having disproportionate (and unaccountable) influence, which is undesirable in a democratic, co-operative model.

B) It's difficult to know when a decision has been made on particular issues. Sometimes, such as with weeks 9-16, there are conflicting points of view. When has a decision been reached in an issue? Is it when the five main reviewers (me, Eoin, Dan, Ines & Nelson) have unanimously agreed? What if people outside these five disagree? What if the conversation is left hanging -- when will the decision be made, and by whom?

### What

The primary purpose of the curriculum committee should be to represent the broader community in making actionable decisions about the curriculum.

It should hold meetings independent of business meetings, so as to not clog it up with curriculum issues, but following a similar [format](https://github.com/foundersandcoders/london-programme/issues/183) with a related [contributing](https://github.com/foundersandcoders/london-programme/issues/181) system.

Anyone is welcome to attend the meetings or discuss the issues, and if they are [members](https://github.com/foundersandcoders/london-programme/issues/147) can vote on items in the agenda. A minimum attendance record should be discussed for course coordinators and curriculum committee members.

A secondary purpose of the curriculum committee should be to hold curriculum review meetings prior to curriculum planning with each cohort. During these the curriculum committee will review the last curriculum, and make proposals for the next curriculum that course coordinators can carry forwards for approval by the current body of students during curriculum planning.

### How

The master-reference has multiple types of issues, some of which are chores, or don't relate to the curriculum, and don't warrant discussion here. 

* All active issues that currently discuss the curriculum should be moved to this `london-curriculum` repo. They will be given `discussion` labels until a time an action-point has been reached, and a proposal is formulated for a committee meeting.
* If a passed proposal effects the master-reference and needs to be captured in a PR there, it should reference the proposal issue from this repo. The contributing.md file of the master-reference will need to be updated to reflect this. Any other proposals for changes to the organisation of the master-reference can be made at a separate meeting.
* Next steps, including creating a charter, as detailed in the [committee procedures](https://github.com/foundersandcoders/london-programme/issues/183) issue.

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#358
