### ISSUE TITLE
Add curriculum planning minutes from Monday May 15th

### ISSUE THREAD

**Issue by joeylouise** [foundersandcoders/london-curriculum#54]

**Comment by bradreeder** [comment]
Closed. See https://github.com/foundersandcoders/master-reference/issues/249

**Comment by jsms90** [comment]
@bradreeder Did we not agree that this was going in `master-reference`, unless London is deciding things alone?

**Comment by bradreeder** [comment]
@jsms90 That's why I closed this issue / PR? :P

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#376
