### ISSUE TITLE
Operational or temporal information for the running of the London curriculum

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-curriculum#6]
Originally raised in the [master-reference](https://github.com/foundersandcoders/master-reference/issues/53).

### Why

The master-reference is intended as a blueprint for the creation of new schools. It is not intended to contain temporal or operational information relevant to the running of a particular school, that needs to be updated every 4 months. 

It has been discussed in [london-programme](https://github.com/foundersandcoders/london-programme/issues/142#issuecomment-274619486) that all operational information, including that of the curriculum, should belong in that repo. 

For reason of separation of concerns, keeping this information up to date should fall within the remit of the curriculum committee. This repo should contain all information relevant to the running of the London campus, while the London-programme repo should contain all information relevant to the running of the London business.

### What

Coursebooks have contained in the past information such as: 

* The calendar
* Facilities
* List of people active in space
* List of responsibilities for current mentors
* The meetup rotas
* Who's on each student project team
* Stop-go-continue notes

As they are temporal or operational information pertinent to the running of the curriculum in London, they should belong in this repo.

### How

* A stop-go-continue folder will be created in this repo to store the stop-go-continue minutes of London FAC's.
* All these files listed above that previously existed in the curriculum gitbook will be moved into this repo before the start of FAC10.

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#359
