### ISSUE TITLE
CFE: Amendment to 'how to run meetups guide'

### ISSUE THREAD

**Issue by BartBucknill** [foundersandcoders/london-curriculum#64]
Currently we have a [how to run meetups guide](https://github.com/foundersandcoders/london-curriculum/blob/4d406b79c97e7fc342aca379b0d382997a26f511/how-to-run-meetups.md), to which we would like to make a few changes before introducing to the current cohort.

- [x] Currently we are not using the sign up form due to various problems, see [issue 73](https://github.com/foundersandcoders/selection-committee/issues/73). We would like to amend the guide to reflect this until we sort out a new sign up solution.

- [x] Explain that we now place a freeCodeCamp sign on one table and a Codewars sign on the other, and direct people to these depending on their interest in order to further facilitate pairing.

- [x] Write on easily visible whiteboard:
- Founders and Coders
- Start finish time: 18:30 - 20:00
- Wifi info: 14palmersroad-1; globetown

- [x] Screen cast founders and coders site during intro, rewrite to indicate desired flow:
- home page for intro. Explain what is FAC's mission.
- click through to [apply page](https://foundersandcoders.com/apply/) and then [London apply page](https://foundersandcoders.com/apply/london) to show where to find application details. Explain that application process details can be found here.
- and then click through to [prerequisites](https://foundersandcoders.com/apply/prerequisites/) and explain that these are good resources for anyone learning to code and use this as opportunity to show that FAC and the meetup are for everyone not just applicants.

- [ ] Explanation of pair programming:
- explain that FAC uses it a lot and that it is a good way to learn from each other, and that is used in production by [companies](https://www.quora.com/What-tech-companies-do-a-lot-of-pair-programming);
- introduce the [backseat driver method](https://github.com/foundersandcoders/master-reference/blob/4432f3823d9168fffc89bb719fe07a75fab9fcaf/coursebook/week-1/pair-programming.md);
- emphasise the benefit of using just one computer;
- note that although we strongly encourage pairing no one is obliged to do so.

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#379
