### ISSUE TITLE
Weeks 10-16 of FAC10 curriculum

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/london-curriculum#7]
### Why

We need to design the latter part of our curriculum around the overarching 'user-journey' of the student. At the point they come back from the reading week students have multiple needs: 

* a need of finding work (freelancing or employment) and improving their employability.
* a need to bring together all they've learnt into practice after an intense 8 week foundation.
* a need to learn new technologies that will help them in finding work.

If we want all 16 students to remain active in this time, and not drop out, we must design these weeks around addressing their needs.

We also need to factor the needs of the organisation. We need to be finding our students work (freelance & employment) and making employer connections:

* To improve our recruitment efforts.
* To improve our reputation in finding our graduates paid projects.
* To keep a portion of each cohort active in the space during the next FAC so there are active mentors in the space.

This proposal for weeks 10-16 attempts to balance these needs through the overarching idea of 'building a portfolio'.

### What

**Weeks 10-12** -- Internal project
* Introduction to Agile workflow + roles
* Design sprint/ working with clients
* User-test with actual users & iterate upon feedback
* Full-stack MVP
* Chance to learn new technologies of choice

**Week 13** -- Employer week (or one week design sprint)
* IP Cortex workshop (3 days)
* Workshops on preparing for interviews, cv, linkedin, etc.

**Week 14** -- One week design sprint
**Week 15** -- Curriculum-planning
**Week 16** -- One week design sprint

### How

* Coursebook, in the master-reference, will need to be updated with outcome of decisions from this proposal.
* Proposal for week's 10-12 final project will need to be finalised for discussion at the next meeting. (https://github.com/foundersandcoders/master-reference/pull/103)
* Arrangements will need to be made with external clients for dates of proposed employer weeks & design sprints.

**Comment by sofer** [comment]
I'll get Anna Freud booked in for Week 14 (May 22nd)

**Comment by jsms90** [comment]
This issue was moved to foundersandcoders/london-programme#361
